### ISSUE TITLE
Allowing User to Specify Text Length and Temperature

### ISSUE THREAD

**Issue by filippofinke** [filippofinke/WordGPT#3]
## Proposed Solution
Add the ability for users to specify the desired text length and temperature for generated responses in the WordGPT office add-on. This feature will provide users with greater control over the output of `text-davinci-003` and enable more precise and targeted responses.

## Task List
- [ ] Implement a text length and temperature option in the WordGPT add-on settings
- [ ] Allow users to input and save their desired text length and temperature values
- [ ] Update the WordGPT interface to use the specified text length and temperature values when generating responses

## Additional Information
Currently, the WordGPT add-on generates responses based on default settings for text length and temperature. While this may be suitable for some users, others may want more control over the output of `text-davinci-003`. Adding the ability to specify text length and temperature will improve the user experience and enable more customized and useful responses.
